version: '3'

services:
  web:
    container_name: mapoo_web
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php

  php:
    container_name: mapoo_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/