name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
        with:
          email: "p.smach99@gmail.com"
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: "mapoo"
          docker_compose_file: ""
          heroku_apps: '[{"imagename":"5656944cb816","appname":"mapoo","apptype":"web"},{"imagename":"6bab445e26b8","appname":"mapoo","apptype":"php"}]' # List of Docker Image name, Heroku app and Heroku app type
        env:
          HD_USERNAME: ${{ secrets.DB_USERNAME }}
          HD_PASSWORD: ${{ secrets.DB_PASSWORD }}
          HD_HOST: ${{ secrets.DB_HOST }}
          HD_DATABASE: ${{ secrets.DATABASE }}
          HD_GGL_API: ${{ secrets.GOOGLE_API }}